### ISSUE TITLE
Could not find implicit value for evidence parameter of type Codec[Any]

### ISSUE THREAD

**Issue by chris-zen** [velvia/msgpack4s#8]
Hi, I am trying to compile the following code but the compiler complains about not finding an implicit value for the evidence parameter of type Codec[Any]:

```scala
  import org.velvia.msgpack._
  import org.velvia.msgpack.AnyCodecs._
  import org.velvia.msgpack.RawStringCodecs._
  import org.velvia.msgpack.CollectionCodecs._

  val mapCodec = new MapCodec[String, Any]

  val bytes = pack[Map[String, Any]](Map("a" -> 1, "b" -> "value"))(mapCodec)
  val m = unpack[Map[String, Any]](bytes)(mapCodec)
```
When I pass the codecs explicitly, then it compiles.

```scala

  import org.velvia.msgpack._
  import org.velvia.msgpack.AnyCodecs._
  import org.velvia.msgpack.RawStringCodecs._
  import org.velvia.msgpack.CollectionCodecs._

  val mapCodec = new MapCodec[String, Any](StringCodec, DefaultAnyCodec)

  val bytes = pack[Map[String, Any]](Map("a" -> 1, "b" -> "value"))(mapCodec)
  val m = unpack[Map[String, Any]](bytes)(mapCodec)
```

Why the StringCodec is taken implicitly but not the DefaultAnyCodec ? May be because it would cancel the other implicits ?

Thanks for your support

**Comment by velvia** [comment]
Hi Christian,

Sorry, the DefaultAnyCodec is not an “implicit object”, therefore it cannot be magically brought in.   The reason for this is because there are two such codecs: the DefaultAnyCodec and DefaultAnyCodecCompat.   Thus, we cannot mark them implicit otherwise the compiler would not know which one to import.

You could kind of get around this by declaring your own implicit:

implicit val anyCodec = DefaultAnyCodec

which would help if you are using this code in multiple places, but for your code below would not save you keystrokes.

-Evan

**Comment by chris-zen** [comment]
Oh, I didn't think about the implicit val, that's right.
Thank you very much and congratulations for the great job and design on this library.

**Comment by velvia** [comment]
Thanks very much!
